//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the MIT License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwakeWindow) DeepCopyInto(out *AwakeWindow) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]Day, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwakeWindow.
func (in *AwakeWindow) DeepCopy() *AwakeWindow {
	if in == nil {
		return nil
	}
	out := new(AwakeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SleepSchedule) DeepCopyInto(out *SleepSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SleepSchedule.
func (in *SleepSchedule) DeepCopy() *SleepSchedule {
	if in == nil {
		return nil
	}
	out := new(SleepSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SleepSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SleepScheduleList) DeepCopyInto(out *SleepScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SleepSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SleepScheduleList.
func (in *SleepScheduleList) DeepCopy() *SleepScheduleList {
	if in == nil {
		return nil
	}
	out := new(SleepScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SleepScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SleepScheduleSpec) DeepCopyInto(out *SleepScheduleSpec) {
	*out = *in
	if in.Awake != nil {
		in, out := &in.Awake, &out.Awake
		*out = make([]AwakeWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Target.DeepCopyInto(&out.Target)
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeRefs != nil {
		in, out := &in.ExcludeRefs, &out.ExcludeRefs
		*out = make([]ResourceRef, len(*in))
		copy(*out, *in)
	}
	if in.TemporaryWake != nil {
		in, out := &in.TemporaryWake, &out.TemporaryWake
		*out = new(TemporaryWake)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SleepScheduleSpec.
func (in *SleepScheduleSpec) DeepCopy() *SleepScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(SleepScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SleepScheduleStatus) DeepCopyInto(out *SleepScheduleStatus) {
	*out = *in
	if in.NextTransition != nil {
		in, out := &in.NextTransition, &out.NextTransition
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SleepScheduleStatus.
func (in *SleepScheduleStatus) DeepCopy() *SleepScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(SleepScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporaryWake) DeepCopyInto(out *TemporaryWake) {
	*out = *in
	out.MaxDuration = in.MaxDuration
	out.DefaultDuration = in.DefaultDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporaryWake.
func (in *TemporaryWake) DeepCopy() *TemporaryWake {
	if in == nil {
		return nil
	}
	out := new(TemporaryWake)
	in.DeepCopyInto(out)
	return out
}
